"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_green)\
$os\
$username\
[](fg:color_green bg:color_teal)\
$directory\
[](fg:color_teal bg:color_sky)\
$git_branch\
$git_status\
[](fg:color_sky bg:color_sapphire)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$python\
[](fg:color_sapphire bg:color_blue)\
$docker_context\
$conda\
[](fg:color_blue bg:color_base)\
$time\
[ ](fg:color_base)\
$line_break$character"""

palette = 'colors'

[palettes.colors]
# Nord accents mapped to your slots
color_green    = "#A3BE8C"  # Nord14
color_teal     = "#8FBCBB"  # Nord7
color_sky      = "#88C0D0"  # Nord8
color_sapphire = "#81A1C1"  # Nord9
color_blue     = "#5E81AC"  # Nord10

# Neutrals
color_base     = "#2E3440"  # Nord0 (background)
color_surface0 = "#3B4252"  # Nord1 (panel/segment bg)
color_text     = "#D8DEE9"  # Nord4 (foreground)

# Alerts
color_red      = "#BF616A"  # Nord11
color_purple   = "#B48EAD"  # Nord15
color_yellow   = "#EBCB8B"  # Nord13


[os]
disabled = false
style = "bg:color_green fg:color_surface0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Kali = " "
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_green fg:color_surface0"
style_root = "bg:color_green fg:color_surface0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_surface0 bg:color_teal"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_sky"
format = '[[ $symbol $branch ](fg:color_surface0 bg:color_sky)]($style)'

[git_status]
style = "bg:color_sky"
format = '[[($all_status$ahead_behind )](fg:color_surface0 bg:color_sky)]($style)'

[nodejs]
symbol = ""
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_sapphire)]($style)'

[c]
symbol = " "
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_sapphire)]($style)'

[rust]
symbol = ""
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_sapphire)]($style)'

[golang]
symbol = ""
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_sapphire)]($style)'

[php]
symbol = ""
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_sapphire)]($style)'

[java]
symbol = " "
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_sapphire)]($style)'

[python]
symbol = ""
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_surface0 bg:color_sapphire)]($style)'

[docker_context]
symbol = ""
style = "bg:color_blue"
# switched to theme fg for consistency/contrast
format = '[[ $symbol( $context) ](fg:color_text bg:color_blue)]($style)'

[conda]
style = "bg:color_blue"
format = '[[ $symbol( $environment) ](fg:color_text bg:color_blue)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_base"
format = '[[  $time ](fg:color_text bg:color_base)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
