# ~/.config/alacritty/themes/phthalo-pastel.toml
# Phthalo Pastel theme for Alacritty
# Soft Catppuccin-like green-first palette

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#1B1F1C"  # deep moss
foreground = "#D9EDE4"  # mint-cream

[colors.cursor]
text   = "#1B1F1C"
cursor = "#D9EDE4"

[colors.selection]
text       = "#1B1F1C"
background = "#2A322E"

[colors.normal]
black   = "#1B1F1C"
red     = "#E28C8C"
green   = "#5BAA89"
yellow  = "#D9D58A"
blue    = "#6DA9A8"
magenta = "#B7A7D9"
cyan    = "#78C4A4"
white   = "#D9EDE4"

[colors.bright]
black   = "#2A322E"
red     = "#F0A1A1"
green   = "#7BCFA4"
yellow  = "#E8E5A8"
blue    = "#84BDC0"
magenta = "#C9BAE6"
cyan    = "#94D8B8"
white   = "#ECF6F1"

